#!/usr/bin/env bash

# Adapted from https://github.com/girst/hardpass-sendHID/blob/master/README.md

# Exit on first error.
set -e

# Treat undefined environment variables as errors.
set -u

modprobe libcomposite

cd /sys/kernel/config/usb_gadget/
mkdir -p g1
cd g1

echo 0x1d6b > idVendor  # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB    # USB2

STRINGS_DIR="strings/0x409"
mkdir -p "$STRINGS_DIR"
echo "serialnumber" > "${STRINGS_DIR}/serialnumber"
echo "manufacturer" > "${STRINGS_DIR}/manufacturer"
echo "Gamepad" > "${STRINGS_DIR}/product"

FUNCTIONS_DIR="functions/hid.usb0"
mkdir -p "$FUNCTIONS_DIR"
echo 0 > "${FUNCTIONS_DIR}/protocol" # Gamepad
echo 0 > "${FUNCTIONS_DIR}/subclass" # No subclass
echo 6 > "${FUNCTIONS_DIR}/report_length" # Report length for gamepad

# Write the report descriptor
# Source: https://www.kernel.org/doc/html/latest/usb/gadget_hid.html
# Write the gamepad report descriptor (converted from https://learn.adafruit.com/custom-hid-devices-in-circuitpython/report-descriptors d)
echo -ne \\x05\\x01\\x09\\x05\\xA1\\x01\\x85\\x04\\x05\\x09\\x19\\x01\\x29\\x10\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x10\\x81\\x02\\x05\\x01\\x15\\x81\\x25\\x7F\\x09\\x30\\x09\\x31\\x09\\x32\\x09\\x35\\x75\\x08\\x95\\x04\\x81\\x02\\xC0 > "${FUNCTIONS_DIR}/report_desc"

CONFIG_INDEX=1
CONFIGS_DIR="configs/c.${CONFIG_INDEX}"
mkdir -p "$CONFIGS_DIR"
echo 250 > "${CONFIGS_DIR}/MaxPower"

CONFIGS_STRINGS_DIR="${CONFIGS_DIR}/strings/0x409"
mkdir -p "$CONFIGS_STRINGS_DIR"
echo "Config ${CONFIG_INDEX}: Gamepad" > "${CONFIGS_STRINGS_DIR}/configuration"

ln -s "$FUNCTIONS_DIR" "${CONFIGS_DIR}/"
ls /sys/class/udc > UDC

chmod 777 /dev/hidg0